# Generated by Django 3.0.3 on 2020-02-08 18:43

import api.models.patient_model
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='Invalid first name', message='First name must not contain any symbols!', regex='^[a-zA-Z- ]+$')])),
                ('last_name', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='Invalid last name', message='Last name must not contain any symbols!', regex='^[a-zA-Z- ]+$')])),
                ('genre', models.CharField(choices=[(api.models.patient_model.Genre['M'], 'masculine'), (api.models.patient_model.Genre['F'], 'feminine')], max_length=15)),
                ('date_of_birth', models.DateTimeField()),
                ('email', models.CharField(max_length=15)),
                ('outstanding_balance', models.FloatField()),
                ('next_appoitment', models.DateTimeField(null=True)),
                ('app_id', models.IntegerField()),
                ('payment_type', models.CharField(choices=[(api.models.patient_model.PaymentTypes['Pending_confirmation'], 'Pending_confirmation'), (api.models.patient_model.PaymentTypes['Direct_Debit'], 'Direct Debit'), (api.models.patient_model.PaymentTypes['One_time'], 'One-time Payment'), (api.models.patient_model.PaymentTypes['Installments'], 'Installments')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_one', models.CharField(max_length=50)),
                ('address_line_two', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=15)),
                ('town', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=15)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Patient', verbose_name='address')),
            ],
        ),
    ]
