# Generated by Django 3.0.3 on 2020-02-09 18:45

import api.models.payment_model
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodgement_date', models.DateTimeField()),
                ('payment_method', models.CharField(choices=[(api.models.payment_model.PaymentMethods['Cash'], 'Cash'), (api.models.payment_model.PaymentMethods['Cheque'], 'Cheque')], max_length=15)),
                ('sort_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(code='Invalid sort code', message='Invalid sort code', regex='^[0-9]+$')])),
                ('account_number', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(code='Invalid account number', message='Invalid account number', regex='^[0-9]+$')])),
                ('bank_name', models.CharField(max_length=15)),
                ('pay', models.FloatField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Patient', verbose_name='payment')),
            ],
        ),
    ]
