# Generated by Django 3.0.3 on 2020-02-09 19:38

import api.models.treatment_models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_type', models.CharField(choices=[(api.models.treatment_models.TreatmentType['Whitening'], 'Whitening'), (api.models.treatment_models.TreatmentType['Cleaning'], 'Cleaning'), (api.models.treatment_models.TreatmentType['Root_Canal'], 'Root Canal'), (api.models.treatment_models.TreatmentType['Braces'], 'Braces'), (api.models.treatment_models.TreatmentType['Late_Cancelation'], 'Late Cancelation'), (api.models.treatment_models.TreatmentType['Filling'], 'Filling')], max_length=50)),
                ('treatment_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DentistSpecialist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialist_name', models.CharField(max_length=15)),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Treatment', verbose_name='treatment')),
            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_time', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Patient', verbose_name='patient')),
                ('treatment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Treatment', verbose_name='treatment')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=15)),
                ('treatment_type', models.CharField(max_length=15)),
                ('treatment_price', models.FloatField()),
                ('appointment_time', models.DateTimeField()),
                ('note', models.CharField(max_length=50)),
                ('dentist_note', models.CharField(max_length=50)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Appointments', verbose_name='appointment')),
                ('refered_specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.DentistSpecialist', verbose_name='refered_specialist')),
            ],
        ),
    ]
