# Generated by Django 3.0.3 on 2020-02-09 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_appointmentcard_appointments_dentistspecialist_treatment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='next_appoitment',
            new_name='next_appointment',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='app_id',
        ),
    ]
