# Generated by Django 3.0.3 on 2020-02-09 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200209_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='pay',
            new_name='amount_pay',
        ),
    ]
