# Generated by Django 2.0.2 on 2020-02-10 23:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200209_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentcard',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='appointmentcard',
            name='refered_specialist',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='treatment_id',
        ),
        migrations.RemoveField(
            model_name='dentistspecialist',
            name='treatment',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='next_appointment',
            new_name='next_appoitment',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='amount_pay',
            new_name='pay',
        ),
        migrations.AddField(
            model_name='patient',
            name='app_id',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AppointmentCard',
        ),
        migrations.DeleteModel(
            name='Appointments',
        ),
        migrations.DeleteModel(
            name='DentistSpecialist',
        ),
    ]
